apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kvib2-poi-map-app-dev
  annotations:
    argocd/app-name: kvib2-poi-map-app-dev
    backstage.io/kubernetes-id: kvib2-poi-map-app
    backstage.io/kubernetes-namespace: kvib2
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh23-demo/kvib2-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/dev-pipelines/ns/kvib2/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/k8s/ns/kvib2/deployments/kvib2-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/#https://github.com/rhdh23-demo/kvib2-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://kvib2-poi-map-app-kvib2.apps.rosa-pzz6v.9nln.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/vyom-soft"
  system: workshop-system-kvib2
  consumesApis:
    - gateway-api-kvib2
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-kvib2
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/vyom-soft"
